//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int ID { get; set; }
        public string Name_City { get; set; }
        public Nullable<int> Country_ID { get; set; }
        public string District { get; set; }
        public string Population { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
