//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.City = new HashSet<City>();
        }
    
        public int ID { get; set; }
        public int Region_ID { get; set; }
        public string Code { get; set; }
        public string Name_Country { get; set; }
        public string Continent { get; set; }
        public double Surface_Area { get; set; }
        public int Indep_Year { get; set; }
        public int Population { get; set; }
        public double Life_Expectancy { get; set; }
        public double GNP { get; set; }
        public double GNPOld { get; set; }
        public string Local_Name { get; set; }
        public string Government_Form { get; set; }
        public string Head_Of_State { get; set; }
        public int Capital { get; set; }
        public string Code2 { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual Region Region { get; set; }
    }
}
