//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOAL
    {
        public int ID_SOAL { get; set; }
        public Nullable<int> ID_KELOMPOKSOAL { get; set; }
        public Nullable<int> ID_TIPESOAL { get; set; }
        public string ISI_SOAL { get; set; }
        public Nullable<int> NILAI_SOAL { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Modified_by { get; set; }
    }
}
